# Generated by Django 4.2.7 on 2023-11-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=10)),
                ('cellphone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price_sold', models.PositiveIntegerField(verbose_name='Price Sold')),
                ('buy_price', models.PositiveIntegerField(verbose_name='Buy Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('bar_code', models.IntegerField(verbose_name='Bar Code')),
                ('minimum_amount', models.PositiveIntegerField(verbose_name='Minimum Amount')),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.category', verbose_name='Name Category')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.suppliers', verbose_name='Suppliers')),
            ],
        ),
    ]
