# Generated by Django 4.2.7 on 2023-12-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0003_remove_user_usuario_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
    ]
