# Generated by Django 4.2.7 on 2023-12-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Venta', '0004_remove_venta_total_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='productos',
            field=models.ManyToManyField(to='Inventario.product'),
        ),
    ]
