# Generated by Django 4.2.7 on 2023-12-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0005_remove_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
