# Generated by Django 4.2.7 on 2023-12-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Venta', '0006_detalleventa_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='productos',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.product'),
            preserve_default=False,
        ),
    ]
